Update BuildUpdate.yml

diff --git a/.github/workflows/BuildUpdate.yml b/.github/workflows/BuildUpdate.yml
--- a/.github/workflows/BuildUpdate.yml
+++ b/.github/workflows/BuildUpdate.yml
@@ -24,8 +24,8 @@ jobs:
     - name: 验证目标存储库
       uses: actions/checkout@v4.2.2
       with:
-        repository: sooyaaabo/Kelee-Loon
-        path: Kelee-Loon
+        repository: sooyaaabo/KeleeOne
+        path: KeleeOne
 
 
 ###### 控制开关
@@ -66,7 +66,7 @@ jobs:
     - name: Loon
       if: env.LOON_SWITCH == 'false'  # 添加开关条件
       run: |
-        for file in Kelee-Loon/Rules/*.list; do
+        for file in KeleeOne/Rules/*.list; do
           if [ -f "$file" ]; then
             sed -i -e '/^PROCESS-NAME/d' "$file"
             file_names=$(basename "$file" .list)
@@ -83,7 +83,7 @@ jobs:
     - name: 批量复刻LOON模块
       if: env.LOON_SWITCH == 'true'  # 添加开关条件
       run: |
-        mkdir -p Kelee-Loon/Plugin
+        mkdir -p KeleeOne/Plugin
 
         
         # 定义插件及其原链接
@@ -251,15 +251,15 @@ jobs:
         # 下载插件并在文件中添加原链接
         for plugin_name in "${!plugins[@]}"; do
             url="${plugins[$plugin_name]}"
-            curl -A "Surge iOS/3367" -L -o "Kelee-Loon/Plugin/${plugin_name}.plugin" "$url"
+            curl -A "Surge iOS/3367" -L -o "KeleeOne/Plugin/${plugin_name}.plugin" "$url"
             
             # 将原链接添加到文件开头
-           # echo "# 原链接 : $url" | cat - "Kelee-Loon/Plugin/$plugin_name.plugin" > temp && mv temp "Kelee-Loon/Plugin/$plugin_name.plugin"
-            sed -i "1s|^|# 原链接 : $url\n|" "Kelee-Loon/Plugin/$plugin_name.plugin"  # 在文件开头添加原链接
+           # echo "# 原链接 : $url" | cat - "KeleeOne/Plugin/$plugin_name.plugin" > temp && mv temp "KeleeOne/Plugin/$plugin_name.plugin"
+            sed -i "1s|^|# 原链接 : $url\n|" "KeleeOne/Plugin/$plugin_name.plugin"  # 在文件开头添加原链接
         done
 
         # 删除 error.log 文件
-        # rm -f Kelee-Loon/Plugin/error.log || echo "No error log to delete"
+        # rm -f KeleeOne/Plugin/error.log || echo "No error log to delete"
 
       
     - name: 提取链接
@@ -269,7 +269,7 @@ jobs:
         mkdir -p ../Script
     
         # 切换到 Plugin 目录
-        cd Kelee-Loon/Plugin
+        cd KeleeOne/Plugin
     
         # 遍历 .plugin 文件并提取 .js 链接
         for file in *.plugin; do
@@ -294,12 +294,12 @@ jobs:
 ###### Commit
     - name: 添加Commits
       run: |
-        cd Kelee-Loon
+        cd KeleeOne
         if [[ -n $(git status -s) ]]; then
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add .
-          git commit -m "Kelee-Loon Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
+          git commit -m "KeleeOne Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
           git push origin HEAD
         else
           echo "No changes to commit."
